compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: "14d"

npmPreapprovedPackages:
  - "@wix/*"

npmRegistryServer: "https://registry.npmjs.org/"
